"""Run every query in a term file against the index and write a Markdown report listing every hit.

  uv run python scripts/term_report.py terms/plutonium.txt                      # -> reports/plutonium-<today>.md
  uv run python scripts/term_report.py terms/plutonium.txt --country RU --out reports/x.md

Term file: one query per line ("label | query" or just the query); "## Heading" lines group terms;
blank lines and "#" comments are ignored. Queries with Cyrillic letters use Russian word-form expansion.
Rerun after new sources land (and after scripts/build_index.py) to refresh the report.
"""
from __future__ import annotations

import argparse
import datetime as dt
import re
import sqlite3
import sys
import time
from pathlib import Path
from typing import List, Optional, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parent))
import searchlib as sl  # noqa: E402
from build_index import DB, ROOT  # noqa: E402

CYR = re.compile(r"[А-Яа-яЁё]")


def read_terms(path: Path) -> List[Tuple[str, str, str]]:
    """[(group, label, query)]"""
    out, group = [], ""
    for line in path.read_text("utf-8").splitlines():
        s = line.strip()
        if not s:
            continue
        if s.startswith("##"):
            group = s.lstrip("#").strip()
            continue
        if s.startswith("#"):
            continue
        label, _, query = s.partition(" | ")
        out.append((group, label.strip(), (query or label).strip()))
    return out


def md_escape(s: str) -> str:
    return re.sub(r"([\\`*_\[\]|<>])", r"\\\1", s or "")


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("termfile", type=Path)
    ap.add_argument("--out", type=Path)
    ap.add_argument("--country")
    ap.add_argument("--source")
    ap.add_argument("--lang")
    ap.add_argument("--from", dest="date_from", default="")
    ap.add_argument("--to", dest="date_to", default="")
    ap.add_argument("--max-snips", type=int, default=10, help="hit snippets listed per document")
    ap.add_argument("--db", type=Path, default=DB)
    a = ap.parse_args(argv)
    today = dt.date.today().isoformat()
    out = a.out or ROOT / "reports" / f"{a.termfile.stem}-{today}.md"
    con = sqlite3.connect(f"file:{a.db}?mode=ro", uri=True)
    csv = lambda v: [x for x in (v or "").split(",") if x]
    f = sl.Filters(csv(a.country), csv(a.source), csv(a.lang), a.date_from, a.date_to)
    fac = sl.facets(con)
    terms = read_terms(a.termfile)

    results = []
    t0 = time.time()
    for group, label, query in terms:
        morph = bool(CYR.search(query))
        try:
            res = sl.search(con, query, f, limit=100000, morph=morph, max_snips=a.max_snips)
            results.append((group, label, query, morph, res, None))
        except (ValueError, sqlite3.OperationalError) as e:
            results.append((group, label, query, morph, None, str(e)))

    L: List[str] = []
    L.append(f"# Term report: {a.termfile.stem} ({today})\n")
    L.append(f"Generated by `scripts/term_report.py {a.termfile}` from `index/corpus.sqlite` "
             f"({fac['range'][2]:,} documents, {fac['range'][0]} to {fac['range'][1]}) in {time.time() - t0:.1f} s. "
             "Rerun after new sources are indexed.\n")
    L.append("Corpus searched:\n")
    L.append("| source | country | docs | from | to |\n|---|---|---:|---|---|")
    for s, c, n, d0, d1 in fac["sources"]:
        L.append(f"| {s} | {c} | {n:,} | {d0} | {d1} |")
    filt = {k: v for k, v in (("country", a.country), ("source", a.source), ("lang", a.lang), ("from", a.date_from),
                              ("to", a.date_to)) if v}
    if filt:
        L.append(f"\nFilters: {filt}")
    L.append("\n## Summary\n")
    L.append("| group | term | query (as run) | docs | hits |\n|---|---|---|---:|---:|")
    for group, label, query, morph, res, err in results:
        if err:
            L.append(f"| {group} | {md_escape(label)} | `{query}` | error: {md_escape(err)} | |")
            continue
        nh = sum(d["hits"] for d in res["results"])
        L.append(f"| {group} | {md_escape(label)} | `{query}`{' (RU forms)' if morph else ''} | {res['total_docs']} | {nh} |")
    total = sum(r[4]["total_docs"] for r in results if r[4])
    L.append(f"\nDocuments with at least one hit, summed over terms: {total}. "
             "Russian queries ran with word-form expansion (" + sl.morph_engine() + "); the FTS expression actually "
             "run is given under each term.\n")
    L.append("## Hits\n")
    for group, label, query, morph, res, err in results:
        L.append(f"### {group}: {md_escape(label)}\n")
        if err:
            L.append(f"Query error: {md_escape(err)}\n")
            continue
        L.append(f"Query `{query}` → `{res['fts'] or '(scan)'}` on `{res['table']}`"
                 + (f" ({res['note']})" if res["note"] else "") + f": **{res['total_docs']} documents**.\n")
        for d in res["results"]:
            who = f", {md_escape(d['speaker'])}" if d["speaker"] else ""
            L.append(f"- **{d['date']}** · {d['country']} · {d['source']} ({md_escape(d['org'] or '')}{who}, {d['lang']}) · "
                     f"{md_escape(d['title'][:160])} · {d['hits']} hit(s)  ")
            for left, hit, right in d["snippets"]:
                L.append(f"  > {md_escape(left)}**{md_escape(hit)}**{md_escape(right)}  ")
            L.append(f"  <{d['url']}>")
        L.append("")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L) + "\n", "utf-8")
    print(f"wrote {out}: {len(terms)} terms, {total} matching documents")
    for group, label, query, morph, res, err in results:
        print(f"  {group:3} {label[:45]:45} {('ERR ' + err) if err else res['total_docs']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
